# Generated by Django 3.1.2 on 2020-10-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144, verbose_name='Name')),
                ('billingAddress', models.TextField(blank=True, null=True, verbose_name='Billing Address')),
                ('isActive', models.BooleanField(default=True, verbose_name='Active')),
                ('website', models.CharField(blank=True, max_length=144, null=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
