# Generated by Django 3.1.2 on 2020-10-06 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0004_auto_20201006_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_manager.profile'),
        ),
    ]
